### PR TITLE
Fix: Issues with remove command

### LINKED ISSUE #289: Bug Remove Commands
**Describe the bug**
Hi, I set up the bot on my pc, when I want to test the whole bot, I saw that the /add command works is not the /remove, for information I didn't touch the command

**To Reproduce**
1. Go to the create ticket
2. Press the /add command to add a member
3. Make the /remove command to remove the limb
4. See the error

**Screenshots**
Link to see the error : https://sourceb.in/9xBqDo3vya

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version : 3.2.2 of the bot

### PR DESCRIPTION
**Pull request by zhiyan114**
Resolves #289

I've used the wrong object during the refactor phase, causing this issue.
Also discovered that removing user does not update the database (which I also missed).
So now, this command should work as intended.

### CODE REVIEW

**Review by Sayrix — APPROVED** [review]
lgtm

**Comment by Sayrix** [comment]
Have you tried your code, by the way?

**Comment by zhiyan114** [comment]
ye, should work

**Comment by Sayrix** [comment]
I renamed the milestone 3.3.0 instead of 5.3.0

**Comment by Sayrix** [comment]
I'll push the version

**Pull request merged**
