### PR TITLE
feat: Source Migration

### PR DESCRIPTION
**Pull request by zhiyan114**
This PR features many legacy migrations includes:
* TypeScript -  Allows the source to be maintained easier #158 
* ORM - More efficient database middleman library #159 
* .env files - More secure way of storing secrets #160
* Telemetry Notices/Switches - #148

Also includes bug fix and small new features.

### CODE REVIEW

**Comment by zhiyan114** [comment]
uhh any reason this was rejected?

**Comment by Sayrix** [comment]
What

**Comment by Sayrix** [comment]
I never closed it

**Comment by Sayrix** [comment]
Ohh fuck i see, that was a bad usage from me of github desktop when i tried to checkout the pr

**Comment by zhiyan114** [comment]
oh, prob a misclick then. Also don't merge it yet, I need to update the docs as well. It's just opened so that you can run a few test yourself to make sure everything is working in-case I missed something during my own test.

**Comment by zhiyan114** [comment]
Also can you send me an invite to the doc as well https://github.com/Sayrix/Ticket-Bot-Docusaurus

**Comment by Sayrix** [comment]
Yep

**Review by Sayrix — APPROVED** [review]
Seems good to me

**Comment by zhiyan114** [comment]
Perfect, just review the docs PR and we'll start merging.

After that, I'll finish couple feature requests and then we can make `v3.0.0` release tag.

**Pull request merged**
