### PR TITLE
feat: Version Checks

### LINKED ISSUE #152: Detect bot updates automatically
**Is your feature request related to a problem? Please describe.**
Some people are not in the discord server and don't know that they can update their ticket-bot

**Describe the solution you'd like**
Maybe make warnings in the console that the bot can be updated

### PR DESCRIPTION
**Pull request by zhiyan114**
Resolves #152 by comparing remote and local git hashes.

### CODE REVIEW

**Comment by Sayrix** [comment]
Hi i don't think that doing a git show is good because people can not have git

**Comment by zhiyan114** [comment]
Oh, ur tutorial shows git clone to get the project, so I assume everyone will be doing that, making git available.

**Comment by Sayrix** [comment]
Yeah but sometimes they just download the zip in the releases page and upload them in a vps that don't have git or into a pterodactyl container

**Comment by zhiyan114** [comment]
Welp, I'm not sure if there's any other way that doesn't involve adding version tags manually.

We could also only support such check if the user has git.

**Comment by Sayrix** [comment]
In the package.json

**Review by Sayrix — CHANGES_REQUESTED** [review]
Use another method instead of using git

**Comment by zhiyan114** [comment]
Oh, you keep versions there. That works, I'll just modify some stuff on my end then.

**Comment by zhiyan114** [comment]
REST-API based version check

**Review by Sayrix — APPROVED** [review]
Not tested but the code seems to be ok, can you ask to someone to try your code or just say me if you tested it ?

**Comment by zhiyan114** [comment]
works pretty good.

**Comment by Sayrix** [comment]
Thank you very much for your contribution

**Pull request merged**
