### PR TITLE
Some refactoring and config checks

### PR DESCRIPTION
**Pull request by zhiyan114**
Did some code refactoring to clear out some random eslint warnings and added `questions`/`ticketTypes` length check so the bot will force the user to fix it.

### CODE REVIEW

**Review by Sayrix — CHANGES_REQUESTED** [review]
For the followUp can you add the error to the /locales ?

**Comment by zhiyan114** [comment]
Alr, should I just google translate it for other lang?

**Comment by Sayrix** [comment]
No just add it in english and let translators to translate it

**Review by Sayrix — APPROVED** [review]

**Comment by zhiyan114** [comment]
> No just add it in english and let translators to translate it

Alr, next time, I'll just fill those with english. The issue with leaving it empty is that the bot will throw error if it tries to pull the empty locale.

**Comment by Sayrix** [comment]
Yeah, maybe use a better i18n thing

**Pull request merged**
