### PR TITLE
Some Feature Updates

### LINKED ISSUE #230: per-category staff roles
Hey 👋

Instead of having a set of staff/ping roles for every category, it would be great if you could configure staff roles per-category. This makes having categories much more worthwhile.

### LINKED ISSUE #248: /Add role
There is a future /add user for now.
Having a command with /add role would be a thing.

And add maybe more then one person/role at the same time instead of sending
/add user (five) times if you want to add 5 people in the channel 🙏

### LINKED ISSUE #323: Closed Ticket Access Issue: Users Unable to Open New Tickets After Closure
**Describe the bug**
There's a bug in the Discord ticket bot system. When a user's ticket is closed but not deleted, they are unable to open new tickets. The chat created for the ticket becomes inaccessible, or an error message indicates that the ticket limit is one, even though they have no open tickets. This issue occurs specifically when a ticket is closed, and the user tries to reopen it using the same message that is only visible to them.

**To Reproduce**
1. Close a user's ticket without deleting it.
2. The user tries to open a new ticket by clicking on the message that was used to open the previously closed ticket, which is only visible to them.
3. The chat for the new ticket becomes inaccessible to the user.
4. Alternatively, an error message is displayed indicating a ticket limit of one, despite no open tickets.

**Expected behavior**
After a ticket is closed, users should be able to open new tickets without encountering access issues or receiving incorrect ticket limit errors.

https://github.com/Sayrix/Ticket-Bot/assets/135083201/42b01180-bd8a-459e-b72f-06fe36a237db

### PR DESCRIPTION
**Pull request by zhiyan114**
Resolves #230

- [ ] @camfsd are you able to give a try and see if the feat works as intended.

Test Note:
* `ticketTypes` should now have `staffRoles` as array (though it can be undefined or empty array if not in use). Confirm with the example config if needed.
* `rolesWhoHaveAccessToTheTickets` is now a "global access" role
------------------------------------------------------
Resolves #248

- [ ] @RaiRaii I would still recommend you to use add commands instead, but in-case you want to mass add users (which does have a couple optimizations), you can use the new `massadd` command. Also do test it to confirm if it's working or not.

Test Note:
* It's a standard slash command: `massadd`
  * It takes in a string argument (which removes the build-in user validation by discord).
  * User ID will be used as input
  * To add multiple users, use the comma `,` as the separator
-----------------------
Resolves #323
Unable to reproduce the said issue, perhaps the fix is already in this branch?

-----------------------
Unrelated
* Added clearDM command to allow users to clean-up history DMs from the bot

### CODE REVIEW

**Comment by zhiyan114** [comment]
@camfsd @RaiRaii Let me know how the software is going before I start the merging process.

**Comment by Sayrix** [comment]
Can you delete the package-lock.json just to see if after that the license compliance passes

**Comment by zhiyan114** [comment]
???????
In that case, then it has to be one of the sub-dependencies that's causing the issue.

**Review by Sayrix — APPROVED** [review]
lgmt, just some copyrights who are still in 2023 (massadd.ts for example)

**Comment by Sayrix** [comment]
Lmk if you want to push the version btw

**Comment by zhiyan114** [comment]
Alr, we'll prob do it after we organize with the new translation feature.

**Pull request merged**
