### PR TITLE
Fixed maxTicketOpened

### PR DESCRIPTION
**Pull request by Musiker15**
Fixed maxTicketOpened if maxTicketOpened is set to higher number than 0

### CODE REVIEW

**Comment by zhiyan114** [comment]
Thanks for the PR, unfortunately, I'll move forward with my PR (#174). But you will get credited for it in next release ^w^
I did some code refactoring and uses `closedby` column as a check instead of `closereason`.

During the time I wrote the query, I didn't see that `closereason` can be disabled by user, and by the time I push out the changes, I forgot that I even used that.

**Review by zhiyan114 — CHANGES_REQUESTED** [review]
You can go head and simplify the `!==` to use `>` instead so that way, the query isn't called if the user decided to give it a negative value.

Also replace `closereason` with `closedby`

**Review by zhiyan114 — APPROVED** [review]
Nevermind, just figured out I'm able to edit files behalf of the user

**Review by Sayrix — APPROVED** [review]
Seems good to me

**Pull request merged**
