### PR TITLE
General fixes/improvements

### PR DESCRIPTION
**Pull request by zhiyan114**
- [x] Fix openTicket throws error if user deletes the message
- [x] Fix error being thrown due to incomplete translation file
- [x] Update dependencies
- [x] Check the existence of `TOKEN` environment variable
- [x] Check if #181 bug was caused by non-latest 18.x of node

### CODE REVIEW

**Comment by Sayrix** [comment]
PR n°200 🎉

**Comment by zhiyan114** [comment]
> PR n°200 🎉

Oh, I just noticed that lol

**Comment by Sayrix** [comment]
On vscode i see it as 2 spaces

**Comment by Sayrix** [comment]
i use tab on all my projects

**Comment by zhiyan114** [comment]
> i use tab on all my projects

Oh, I moved away from tab because on some of my projects (especially involving python), mixing tab and space can cause all kinds of issue and space is just easier to deal with.

But ye, I'll revert it

**Comment by zhiyan114** [comment]
Alr, we should be good now.

**Review by Sayrix — APPROVED** [review]

**Pull request merged**
