### PR TITLE
General Maintenance

### LINKED ISSUE #339: Ticket permissions resetted when ticket parent change
Problem is high because somebody when claim ticket from staff client who open ticket lost acces in ticket it cant see ticket.

### PR DESCRIPTION
**Pull request by zhiyan114**
* Resolves #339
* Updated Packages
* Some workaround done to keep the tsc happy (caused by some TSC engine bug or @types/node)

### CODE REVIEW

**Review by Sayrix — APPROVED** [review]
lgtm

**Comment by zhiyan114** [comment]
Just need to check a couple more things on why TSC is yelling at nothing

**Comment by Sayrix** [comment]
You can't transpile ?

**Comment by zhiyan114** [comment]
Ye type check is complaining about a non-existing errors on @node/type after upgrading the package.

**Comment by zhiyan114** [comment]
Just tested and it looks like it could be a typescript engine error, we'll just keep the older version for now

**Comment by Sayrix** [comment]
Is there any open issue on typescript's github about that?

**Comment by zhiyan114** [comment]
I couldn't find any tbh, this feels like an edge case where it reproduceable on certain repo but not others.

I tested on my other bot project, and I got a completely different non-existing errors.

**Pull request merged**
