### PR TITLE
Feat: PostgreSQL Support & fixes

### LINKED ISSUE #156: Bot crashes if webhook already exist for log channel that isn't accessible by the bot
In certain condition, a webhook that is created under the log channel may be inaccessible by the ticket bot; thus, throwing the error. Since the algorithm detects that the channel already has a webhook, it will not create one that is usable.

I can push out a fix to my current PR (#155)

Context:
musiker15 - 

```
node index.js

████████╗██╗ ██████╗██╗  ██╗███████╗████████╗    ██████╗  ██████╗ ████████╗
╚══██╔══╝██║██╔════╝██║ ██╔╝██╔════╝╚══██╔══╝    ██╔══██╗██╔═══██╗╚══██╔══╝
   ██║   ██║██║     █████╔╝ █████╗     ██║       ██████╔╝██║   ██║   ██║   
   ██║   ██║██║     ██╔═██╗ ██╔══╝     ██║       ██╔══██╗██║   ██║   ██║   
   ██║   ██║╚██████╗██║  ██╗███████╗   ██║       ██████╔╝╚██████╔╝   ██║   
   ╚═╝   ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝   ╚═╝       ╚═════╝  ╚═════╝    ╚═╝
                 https://github.com/Sayrix/ticket-bot

Connecting to Discord...
🚀  The bot is ready! Logged in as MSK Support#6882 (456456456456)
🌟  You can leave a star on GitHub: https://github.com/Sayrix/ticket-bot 
📖  Documentation: https://doc.ticket.pm 
⛅  Host your ticket-bot by being a sponsor from 1$/month: https://github.com/sponsors/Sayrix 
💖  Thanks to our sponsors: VespidEmperor, BlutwurstPro, Musiker15, LostServices, MCZ-Le-J, nunofaria13, ZeaDRGOD, BgMonsterXx, GapsaW, Lucas6635, nicolasbaud
✅  Connected to WebSocket server.
✅  Successfully registered application commands.
TypeError: Cannot read properties of undefined (reading 'send')
    at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:42:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'send')
      at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:42:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} undefined
TypeError: Cannot read properties of undefined (reading 'send')
    at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:80:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'send')
      at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:80:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} undefined
TypeError: Cannot read properties of undefined (reading 'send')
    at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:99:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'send')
      at Client.log (/opt/discordBot/msk_scripts/ticketsystem/utils/logs.js:99:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} undefined
```

### PR DESCRIPTION
**Pull request by zhiyan114**
PostgreSQL is a popular choice for remote database and better than mysql.

PR also a resolves #156

### CODE REVIEW

**Comment by Sayrix** [comment]
In the comments of your driver postgre you say that it's taken from the quick.db pre-release but in that case why not wait for quick.db to support it directly rather than using experimental code?

**Comment by zhiyan114** [comment]
It seems like all database driver formats are the same for the library. It's stable enough, they're probably waiting a bit longer to add other changes before releasing it.

**Comment by Sayrix** [comment]
Can you try your code and say me if every functions of ticket-bot works ?

**Comment by Sayrix** [comment]
Especially the emojis in the db

**Comment by zhiyan114** [comment]
Sure, though, I'll be later tonight since I won't be available near the dev PC for the day

**Comment by zhiyan114** [comment]
The emoji won't be a problem, since Postgres already know how to handle that. The only issue I found is the default config table name that I initially set to, which conflicts with SQL's keyword. Other than that, it works like normal.

I'll def make another PR once quick.db push out the driver to clean stuff up, tho I do recommend you to plan and move away from `squick.db` because how inefficient it is at using database.

**Pull request merged**
