### PR TITLE
Fixed TICKETCOUNT

### LINKED ISSUE #343: ticket count mismatch
**Describe the bug**
After the bot crashes with an error, the ticket count can become mismatched. `TICKETCOUNT` in the channel name is one less than `TICKETCOUNT` in the category description, displayed in the first embed in the ticket channel.

**To Reproduce**
1. Run the bot with an invalid ID in a `cantAccess` field.
2. Open a ticket in the category with the invalid ID configured.
3. Re-run the bot with the invalid ID removed.
4. Open another ticket in the same category. Observe.

After reproducing these steps, the ticket count in the channel name will be the same as the one that was created before the crash, however the ticket count in the description will have incremented.

image

**Expected behavior**
The ticket count in the channel name and the channel description are consistent. As an identifier, they should match.

**Desktop:**
 - OS: Win11E 22H2
 - ticket-bot v3.3.0

### PR DESCRIPTION
**Pull request by Uo1428**
Fixed #343

### CODE REVIEW

**Review by Sayrix — APPROVED** [review]

**Comment by Sayrix** [comment]
Thank you for your contribution @Uo1428 have you tried if it fixed the bug or it's untested ?

**Comment by Uo1428** [comment]
it will solve the problem

**Comment by Sayrix** [comment]
If you have screenshots that would be great

**Review by Sayrix — APPROVED** [review]

**Comment by Sayrix** [comment]
Hi can you setup a github sponsors on your profile @Uo1428 ?

**Comment by Uo1428** [comment]
Sure

**Comment by Uo1428** [comment]
My request is pending, why do you need this information?

**Comment by Sayrix** [comment]
Hi, this is to sponsor you for your PR

**Comment by Uo1428** [comment]
Oh, I use patreon

**Pull request merged**
