### PR TITLE
Integration with Django

### PR DESCRIPTION
**Pull request by Rafaelh9siX**
I made an integration with django that doesn't interfere with the code or with the tables already created in the database.

An auxiliary table is created to insert the new data, and it is possible to perform queries and CRUDs by Django Admin.

### CODE REVIEW

**Comment by Sayrix** [comment]
Why ????

**Comment by Sayrix** [comment]
Oh, i just looked, I thought you re writed the bot in python but no

**Comment by zhiyan114** [comment]
Hey, just wondering what benefits will integrating with Django bring?
I don't really see a need for a webserver so I'm just asking this (especially non-node stack).

**Comment by Rafaelh9siX** [comment]
I used Django just to be easier/faster to create, and because I'm still new to javascript.

I have a friend who uses this bot a lot with his team, and a webserver ends up being greatly missed, because whenever they need to perform a query they need to access the database directly, create a script, copy the user ID, etc...

As I'm still gaining experience, I used this idea and ended up doing it to learn.

**Comment by zhiyan114** [comment]
If query is needed, you can always run an external database and connect directly to it along with the bot. For any other direct bot interactions and callbacks, I can create a much less complicated REST API/webhook (Express) or Message Queue (AMQP) System.

I like the feature, but it's just adding too much complexity to the codebase without knowing if other users will actually use this. As always if @Sayrix is okay with this, we can add it.

**Review by Sayrix — CHANGES_REQUESTED** [review]
Is it possible to tree your project in ./django/ instead of putting it in the ticket-bot root?

**Comment by Rafaelh9siX** [comment]
Moved to ./django/ in the last push

> If query is needed, you can always run an external database and connect directly to it along with the bot. For any other direct bot interactions and callbacks, I can create a much less complicated REST API/webhook (Express) or Message Queue (AMQP) System.
> 
> I like the feature, but it's just adding too much complexity to the codebase without knowing if other users will actually use this. As always, if @Sayrix is okay with this, we can add it.

The way I did it, I don't think it's the best, but since I didn't want to interfere with the bot's operation and I don't have much knowledge in javascript, I ended up doing this "workaround" lol

**Review by Sayrix — CHANGES_REQUESTED** [review]
Can you sync the branch, i think there are conflicts with some changes that we made

**Comment by Rafaelh9siX** [comment]
I had changed some files by mistake, now they must be with the changes you made.

**Review by Sayrix — CHANGES_REQUESTED** [review]
Can you also move the readme of django to DJANGO.md ?

**Comment by Rafaelh9siX** [comment]
Moved the readme into the Django folder

**Review by Sayrix — APPROVED** [review]

**Review by zhiyan114 — CHANGES_REQUESTED** [review]
Hey, mind cleaning up `.gitignore` a bit?
I feel like not all of the files/directories that's listed will be generated when running the Django.
If I'm wrong, let me know.

Also `DJANGO.md` and `django/README.md` seems to be a duplicate file.

**Comment by Rafaelh9siX** [comment]
> * [ ]  Hey, mind cleaning up `.gitignore` a bit?
>   I feel like not all of the files/directories that's listed will be generated when running the Django.
>   If I'm wrong, let me know.

I was using the .gitignore python template, now it should be just the essentials
> * [ ]  `DJANGO.md` and `django/README.md` seems to be a duplicate file

I removed the DJANGO.md
> * [ ]  `django/trigger.py` seems to have `print("aaaaa")`, not sure if you accidently left it there during development.

This was a print used for debugging that I ended up forgetting to delete
> * [ ]  Both `django/tickets/tests.py` and `django/tickets/views.py` are incomplete. if no test will be written, you can go head and delete it.

They are standard Django files, but as they won't be needed I removed them

**Review by zhiyan114 — APPROVED** [review]
Alright we good, I'll go head and merge it.

**Pull request merged**
